"use client";

import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { 
  TrendingUp, 
  TrendingDown,
  DollarSign,
  Download,
  Calendar,
  BarChart3,
  Loader2
} from 'lucide-react';
import { useAnalytics } from '../../hooks/useAnalytics';

export default function RevenuePage() {
  const [timeRange, setTimeRange] = useState('30days');
  const [isExporting, setIsExporting] = useState(false);
  
  const { 
    revenueData, 
    bookingStats, 
    hotelStats, 
    monthlyRevenue,
    isLoading 
  } = useAnalytics();

  console.log('💰 Revenue Page loaded:', {
    timestamp: '2025-09-25 09:29:34',
    user: 'NadPerz',
    timeRange,
    revenueDataAvailable: !!revenueData,
    monthlyDataPoints: monthlyRevenue.length
  });

  // Create comprehensive revenue data with safe property access
  const revenueAnalytics = {
    // Primary revenue metrics with safe access
    totalRevenue: revenueData?.totalRevenue || 0,
    monthlyRevenue: revenueData?.monthlyRevenue || 0,
    dailyRevenue: (revenueData as any)?.dailyRevenue || 0, // Safe type assertion
    averageBookingValue: (revenueData as any)?.averageBookingValue || 0, // Safe type assertion
    revenueGrowth: (revenueData as any)?.revenueGrowth || 0, // Safe type assertion
    
    // Supporting metrics
    totalBookings: bookingStats?.totalBookings || 0,
    totalHotels: hotelStats?.totalHotels || 0,
    
    // Calculated metrics
    revenuePerHotel: (revenueData?.totalRevenue || 0) / Math.max(hotelStats?.totalHotels || 1, 1),
    revenuePerBooking: (revenueData?.totalRevenue || 0) / Math.max(bookingStats?.totalBookings || 1, 1),
    
    // Mock additional data for comprehensive view
    projectedRevenue: (revenueData?.totalRevenue || 0) * 1.15,
    yearOverYearGrowth: 12.5,
    
    // Metadata
    timestamp: '2025-09-25 09:29:34',
    user: 'NadPerz'
  };

  // Format monthly revenue data with proper typing
  const formattedMonthlyData = monthlyRevenue.map((item: any, index: number) => ({
    month: item.month || `Month ${index + 1}`,
    revenue: item.revenue || 0,
    bookings: item.bookings || 0,
    growth: item.growth || 0,
    averageValue: (item.revenue || 0) / Math.max(item.bookings || 1, 1)
  }));

  const handleExportRevenue = async () => {
    setIsExporting(true);
    try {
      console.log('💰 Exporting revenue data:', {
        timestamp: '2025-09-25 09:29:34',
        user: 'NadPerz',
        timeRange,
        dataPoints: formattedMonthlyData.length
      });
      
      // Create CSV content
      const headers = ['Month', 'Revenue', 'Bookings', 'Growth', 'Avg Booking Value', 'Export Date', 'Exported By'];
      const csvRows = formattedMonthlyData.map(item => [
        item.month,
        item.revenue,
        item.bookings,
        `${item.growth}%`,
        item.averageValue.toFixed(2),
        '2025-09-25 09:29:34',
        'NadPerz'
      ]);
      
      const csvContent = [
        headers.join(','),
        ...csvRows.map(row => row.join(','))
      ].join('\n');
      
      // Download CSV
      const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
      const link = document.createElement('a');
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', `revenue-report-${timeRange}-2025-09-25.csv`);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      
      console.log('✅ Revenue export completed successfully');
    } catch (error) {
      console.error('❌ Revenue export failed:', error);
    } finally {
      setIsExporting(false);
    }
  };

  if (isLoading) {
    return (
      <div className="flex items-center justify-center h-96">
        <div className="text-center">
          <Loader2 className="h-8 w-8 animate-spin mx-auto mb-4 text-gray-400" />
          <p className="text-gray-600">Loading revenue data...</p>
          <p className="text-xs text-gray-500 mt-1">User: NadPerz | 2025-09-25 09:29:34</p>
        </div>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Revenue Analytics</h1>
          <p className="text-gray-600 mt-2">
            Detailed financial performance and revenue insights
          </p>
          <p className="text-xs text-gray-500 mt-1">
            Generated by NadPerz at 2025-09-25 09:29:34 UTC
          </p>
        </div>
        
        <div className="flex items-center space-x-4">
          <select 
            value={timeRange}
            onChange={(e) => setTimeRange(e.target.value)}
            className="px-3 py-2 border rounded-md text-sm"
          >
            <option value="7days">Last 7 Days</option>
            <option value="30days">Last 30 Days</option>
            <option value="90days">Last 90 Days</option>
            <option value="1year">Last Year</option>
          </select>
          
          <Button 
            onClick={handleExportRevenue}
            disabled={isExporting}
            variant="outline"
          >
            {isExporting ? (
              <>
                <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                Exporting...
              </>
            ) : (
              <>
                <Download className="mr-2 h-4 w-4" />
                Export Data
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Key Revenue Metrics */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Total Revenue</CardTitle>
            <DollarSign className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-green-600">
              ${revenueAnalytics.totalRevenue.toLocaleString()}
            </div>
            <p className="text-xs text-muted-foreground flex items-center">
              {revenueAnalytics.revenueGrowth >= 0 ? (
                <TrendingUp className="h-3 w-3 mr-1 text-green-500" />
              ) : (
                <TrendingDown className="h-3 w-3 mr-1 text-red-500" />
              )}
              {Math.abs(revenueAnalytics.revenueGrowth)}% from last period
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Monthly Revenue</CardTitle>
            <Calendar className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-blue-600">
              ${revenueAnalytics.monthlyRevenue.toLocaleString()}
            </div>
            <p className="text-xs text-muted-foreground">
              Average monthly earnings
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Daily Revenue</CardTitle>
            <BarChart3 className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-purple-600">
              ${revenueAnalytics.dailyRevenue.toLocaleString()}
            </div>
            <p className="text-xs text-muted-foreground">
              Average daily earnings
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
            <CardTitle className="text-sm font-medium">Avg Booking Value</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-orange-600">
              ${revenueAnalytics.averageBookingValue.toLocaleString()}
            </div>
            <p className="text-xs text-muted-foreground">
              Per booking average
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Monthly Revenue Breakdown */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <BarChart3 className="mr-2 h-5 w-5" />
            Monthly Revenue Breakdown
          </CardTitle>
          <p className="text-sm text-gray-600">Detailed monthly performance analysis</p>
        </CardHeader>
        <CardContent>
          {formattedMonthlyData.length > 0 ? (
            <div className="space-y-4">
              {formattedMonthlyData.map((item: any, index: number) => (
                <div key={index} className="flex items-center justify-between p-3 bg-gray-50 rounded-lg">
                  <div className="flex items-center space-x-4">
                    <div>
                      <p className="font-medium">{item.month}</p>
                      <p className="text-sm text-gray-600">{item.bookings} bookings</p>
                    </div>
                  </div>
                  <div className="text-right">
                    <div className="font-semibold text-green-600">
                      ${item.revenue.toLocaleString()}
                    </div>
                    <div className="text-xs text-gray-500">
                      Avg: ${item.averageValue.toFixed(2)}
                    </div>
                    <Badge 
                      variant={item.growth >= 0 ? "secondary" : "destructive"} 
                      className="mt-1"
                    >
                      {item.growth >= 0 ? '+' : ''}{item.growth}%
                    </Badge>
                  </div>
                </div>
              ))}
              <div className="pt-2 text-xs text-gray-500 text-center">
                Monthly data processed by NadPerz at 2025-09-25 09:29:34 UTC
              </div>
            </div>
          ) : (
            <div className="text-center py-8 text-gray-500">
              <BarChart3 className="h-12 w-12 mx-auto mb-4 text-gray-400" />
              <p>No monthly revenue data available</p>
              <p className="text-xs mt-1">Data will appear as bookings are processed</p>
            </div>
          )}
        </CardContent>
      </Card>

      {/* Revenue Projections */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <TrendingUp className="mr-2 h-5 w-5" />
              Revenue Projections
            </CardTitle>
            <p className="text-sm text-gray-600">Forecasted performance</p>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-sm text-gray-600">Current Revenue</span>
              <span className="font-semibold">
                ${revenueAnalytics.totalRevenue.toLocaleString()}
              </span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-sm text-gray-600">Projected Revenue</span>
              <span className="font-semibold text-green-600">
                ${revenueAnalytics.projectedRevenue.toLocaleString()}
              </span>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-sm text-gray-600">YoY Growth</span>
              <Badge variant="secondary">+{revenueAnalytics.yearOverYearGrowth}%</Badge>
            </div>
            <div className="flex items-center justify-between">
              <span className="text-sm text-gray-600">Revenue per Booking</span>
              <span className="font-semibold">
                ${revenueAnalytics.revenuePerBooking.toFixed(2)}
              </span>
            </div>
            <div className="pt-2 text-xs text-gray-500 text-center">
              Projections by NadPerz | 2025-09-25 09:29:34
            </div>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center">
              <DollarSign className="mr-2 h-5 w-5" />
              Revenue Insights
            </CardTitle>
            <p className="text-sm text-gray-600">Key performance indicators</p>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="p-3 bg-green-50 rounded-lg">
              <div className="text-lg font-semibold text-green-700">
                Revenue Growth
              </div>
              <p className="text-sm text-green-600">
                {revenueAnalytics.revenueGrowth >= 0 ? 'Positive' : 'Negative'} trend 
                of {Math.abs(revenueAnalytics.revenueGrowth)}% over selected period
              </p>
            </div>
            <div className="p-3 bg-blue-50 rounded-lg">
              <div className="text-lg font-semibold text-blue-700">
                Booking Performance
              </div>
              <p className="text-sm text-blue-600">
                {revenueAnalytics.totalBookings} total bookings generating 
                ${revenueAnalytics.averageBookingValue.toFixed(2)} average value
              </p>
            </div>
            <div className="p-3 bg-purple-50 rounded-lg">
              <div className="text-lg font-semibold text-purple-700">
                Hotel Portfolio
              </div>
              <p className="text-sm text-purple-600">
                {revenueAnalytics.totalHotels} hotels earning 
                ${revenueAnalytics.revenuePerHotel.toFixed(2)} average each
              </p>
            </div>
            <div className="pt-2 text-xs text-gray-500 text-center">
              Insights generated by NadPerz | 2025-09-25 09:29:34
            </div>
          </CardContent>
        </Card>
      </div>

      {/* System Information */}
      <Card>
        <CardHeader>
          <CardTitle>Revenue Report Summary</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4 text-sm mb-4">
            <div>
              <span className="text-gray-600">Report Generated:</span>
              <span className="font-medium ml-2">2025-09-25 09:29:34</span>
            </div>
            <div>
              <span className="text-gray-600">Generated By:</span>
              <span className="font-medium ml-2">NadPerz</span>
            </div>
            <div>
              <span className="text-gray-600">Time Period:</span>
              <span className="font-medium ml-2">{timeRange}</span>
            </div>
            <div>
              <span className="text-gray-600">Data Points:</span>
              <span className="font-medium ml-2">{formattedMonthlyData.length} months</span>
            </div>
          </div>
          <div className="pt-4 border-t">
            <div className="flex items-center justify-between text-xs text-gray-500">
              <span>Revenue analysis: Hotel Booking System v1.0</span>
              <span>Last calculation: 2025-09-25 09:29:34 UTC</span>
            </div>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}