export enum UserRole {
  BUSINESS_OWNER = 'BUSINESS_OWNER',
  BRANCH_MANAGER = 'BRANCH_MANAGER',
  CONTENT_MANAGER = 'CONTENT_MANAGER',
  EVENT_MANAGER = 'EVENT_MANAGER',
  RESERVATIONS_MANAGER = 'RESERVATIONS_MANAGER',
}

export enum UserType {
  TRAVELER = 'TRAVELER',
  BUSINESS_USER = 'BUSINESS_USER',
}
